### ISSUE TITLE
重构Web线程池配置文件命名

### ISSUE THREAD

**Issue by magestacks** [opengoofy/hippo4j#1015]
当前配置 Web 线程池需要依赖容器名称，如下：

```yaml
spring:
  dynamic:
    thread-pool:
      # tomcat、undertow、jetty 三种容器线程池，任选其一
      undertow:
```

考虑到配置不应该随着项目架构而变动，所以修改为：

```yaml
spring:
  dynamic:
    thread-pool:
      web:
```
