### ISSUE TITLE
[Bug]服务端容器里某个目录或文件占用过大空间

### ISSUE THREAD

**Issue by Skqing** [opengoofy/hippo4j#1453]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Environment

Linux

### Hippo4j version

1.5.0

### What happened

查看docker占用
![image](https://github.com/opengoofy/hippo4j/assets/1713001/a0f5565b-2423-4eac-b4bb-79ef1372f414)
发现是日志文件太大了
![image](https://github.com/opengoofy/hippo4j/assets/1713001/799f84dc-adf5-4596-b2e2-0e5c9b6e2196)

进入到容器里面查看占用
![image](https://github.com/opengoofy/hippo4j/assets/1713001/9bc41b38-2a17-48a9-8c52-f31d16e0c276)

以为/etc/hosts是个目录，结果提示不是目录
但如果是文件/etc/hosts不应该会57G啊

### How to reproduce

```
version: '3.7'

services:
  hippo4j-server:
    image: hippo4j/hippo4j-server:1.5.0
    restart: always
    hostname: hippo4j-server
    container_name: hippo4j-server
    ports:
      - 6691:6691
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024m
    environment:
      DATASOURCE_MODE: mysql
      DATASOURCE_HOST: xxxxx
      DATASOURCE_PORT: xxxx
      DATASOURCE_DB: xxxxx
      DATASOURCE_USERNAME: xxxx
      DATASOURCE_PASSWORD: xxxx
    networks:
      mynet:
        ipv4_address: 172.20.0.10
    volumes:
            #- /home/logs/hippo4j:/opt/hippo4j/logs #这个目录主要是JVM的日志
      - /home/logs/hippo4j:/opt/hippo4j/bin/logs/
      - /home/logs/hippo4j:/opt/hippo4j/hippo4j.home_IS_UNDEFINED/logs/ #hippo4j.home本来是个变量但没有被定义，这个是BUG https://github.com/opengoofy/hippo4j/issues/1419
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
networks:
  mynet:
    external: true
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *
