### ISSUE TITLE
[Question] 无法发送告警和通知信息

### ISSUE THREAD

**Issue by Skqing** [opengoofy/hippo4j#1469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Question

JAR v1.5.0
hippo4j后台 v1.5.0

1.这里的配置 https://hippo4j.cn/docs/user_docs/getting_started/config/hippo4j-config-start
这里的钉钉要求配置token和secret
```
spring:
  profiles:
    active: dev

  dynamic:
    thread-pool:
      # 是否开启动态线程池
      enable: true
      # 是否打印 banner
      banner: true
      # 是否开启线程池数据采集，对接 Micrometer、ES、Log 等
      collect: true
      # 检查线程池状态，是否达到报警条件，单位毫秒
      check-state-interval: 3000
      # 通知报警平台，请替换为自己创建的群机器人
      notify-platforms:
        - platform: 'WECHAT'
          token: xxx
        - platform: 'DING'
          token: xxx
          secret: xxx  # 加签专属
```

2.管理后台的配置窗口
![image](https://github.com/opengoofy/hippo4j/assets/1713001/4b17fe13-3926-45f5-b081-86804e0fb4b1)
这里的钉钉配置只有一个token

3.代码里是要求getSecretKey和getSecret
![image](https://github.com/opengoofy/hippo4j/assets/1713001/5fecfcb3-ce20-4ef3-99c0-746d6033e927)

所以到底按哪里的配置？目前为止所有地方都配置了，但在管理后台修改配置仍然发不了通知，并且程序里丢弃线程也没发告警信息。
或者说管理后台的配置和配置文件里的配置分别是什么作用呢？

**Comment by magestacks** [comment]
先了解清楚配置中心模式和无中间件模式的区别。

**Comment by Skqing** [comment]
> 先了解清楚配置中心模式和无中间件模式的区别。
看了文档无中间件模式包含配置中心模式的功能啊，两者都有报警功能不是吗？在文档“通知报警”就是按照无中间件模式配置的，我是按无中间件模式配置的为什么不起作用呢？这跟你的模式原理有什么关系？难道看文档看不行吗？

**Comment by Skqing** [comment]
https://hippo4j.cn/docs/user_docs/user_guide/notify
https://hippo4j.cn/docs/user_docs/getting_started/difference/
这两个文档我都看了，并不能解决问题

**Comment by magestacks** [comment]
你给的配置是配置中心模式：
```yaml
spring:
  profiles:
    active: dev

  dynamic:
    thread-pool:
      # 是否开启动态线程池
      enable: true
      # 是否打印 banner
      banner: true
      # 是否开启线程池数据采集，对接 Micrometer、ES、Log 等
      collect: true
      # 检查线程池状态，是否达到报警条件，单位毫秒
      check-state-interval: 3000
      # 通知报警平台，请替换为自己创建的群机器人
      notify-platforms:
        - platform: 'WECHAT'
          token: xxx
        - platform: 'DING'
          token: xxx
          secret: xxx  # 加签专属
```

下边截图是无中间件依赖模式，无中间件依赖只需要配置 Token 就行了。如果还是不行，请自行Debug。
