### ISSUE TITLE
定义动态线程池时，抽象默认配置

### ISSUE THREAD

**Issue by pirme** [opengoofy/hippo4j#572]
动态线程池抽象默认配置，仅需要配置线程池 id 和线程工厂前缀即可创建线程池。

```properties
spring.dynamic.thread-pool.default.core-pool-size=2
spring.dynamic.thread-pool.default.maximum-pool-size=4
spring.dynamic.thread-pool.default.alarm=true
...

spring.dynamic.thread-pool.executors[0].thread-pool-id=message-consume
spring.dynamic.thread-pool.executors[0].thread-name-prefix=message-consume
```

**Comment by agentart** [comment]
完成。配置线程池最少只有一个属性 threadPoolId 即可。

```yml
spring:
  dynamic:
    thread-pool:
      default-executor:
        core-pool-size: 2
        maximum-pool-size: 10
        blocking-queue: ResizableCapacityLinkedBlockingQueue
        execute-time-out: 100
        keep-alive-time: 6691
        queue-capacity: 1
        rejected-handler: AbortPolicy
        active-alarm: 90
        capacity-alarm: 85
        alarm: true
        allow-core-thread-time-out: true
        notify:
          interval: 5
          receives: chen.ma
      executors:
      - thread-pool-id: message-consume
        core-pool-size: 5
        execute-time-out: 1000
        notify:
          interval: 6
          receives: chen.ma
      - thread-pool-id: message-produce
```
