### ISSUE TITLE
使用k8s部署，设置私有mysql数据库，部署之后还是走的内置h2数据库。

### ISSUE THREAD

**Issue by napolv-diors** [opengoofy/hippo4j#801]
想用k8s部署项目，走私有mysql数据库配置，结果走的还是内置h2数据库。

部署的脚本如下：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hippo4j-server
  name: hippo4j-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hippo4j-server
  template:
    metadata:
      labels:
        app: hippo4j-server
    spec:
      containers:
        - image: hippo4j/hippo4j-server:latest
          imagePullPolicy: Always
          env:
          - name: DATASOURCE_MODE
            value: "mysql"
          - name: DATASOURCE_HOST
            value: "xxx"
          - name: DATASOURCE_PORT
            value: "xxx"
          - name: DATASOURCE_DB
            value: "hippo4j_manager"
          - name: DATASOURCE_USERNAME
            value: "root"
          - name: DATASOURCE_PASSWORD
            value: "xxx"
          name: hippo4j-server
          ports:
            - containerPort: 6691
              protocol: TCP
          resources:
            limits:
              memory: "2048Mi"
            requests:
              memory: "2048Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hippo4j-server
  name: hippo4j-server
spec:
  ports:
    - name: http
      port: 6691
      protocol: TCP
      targetPort: 6691
      nodePort: 32691
  selector:
    app: hippo4j-server
  sessionAffinity: None
  type: NodePort
```

部署之后项目的启动信息中输出的数据库是h2
```
root     4032818 4032799  0 14:32 ?        00:00:00 sh -c java -jar  -Xloggc:${BASE_DIR}/hippo4j_gc.log -verbose:gc -XX:+PrintGCDetails      -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation      -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M      -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${BASE_DIR}/java_heapdump.hprof      -Xms1024m -Xmx1024m -Xmn512m      -Dhippo4j.standalone=true -Dhippo4j.home=${BASE_DIR}  hippo4j-server.jar     --server.max-http-header-size=524288     --server.tomcat.basedir=${BASE_DIR}/tomcat     --logging.config=${BASE_DIR}/logback.xml     --spring.profiles.active=h2     --spring.datasource.url=jdbc:h2:file:${BASE_DIR}/h2_hippo4j;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MYSQL
root     4032834 4032818  3 14:32 ?        00:00:34 java -jar -Xloggc:/opt/hippo4j/hippo4j_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/hippo4j/java_heapdump.hprof -Xms1024m -Xmx1024m -Xmn512m -Dhippo4j.standalone=true -Dhippo4j.home=/opt/hippo4j hippo4j-server.jar --server.max-http-header-size=524288 --server.tomcat.basedir=/opt/hippo4j/tomcat --logging.config=/opt/hippo4j/logback.xml --spring.profiles.active=h2 --spring.datasource.url=jdbc:h2:file:/opt/hippo4j/h2_hippo4j
```
